version: '0.9.0-rev{build}'
image: Visual Studio 2019
clone_depth: 5
environment:
  TARGET: x86_64-pc-windows-msvc
  RUST_TOOLCHAIN: nightly
  RUST_BACKTRACE: full
  matrix:
  - PYTHON: "C:\\Python37-x64"
  - PYTHON: "C:\\Python38-x64"
  - PYTHON: "C:\\Python39-x64"
  - PYTHON: "C:\\Python310-x64"

cache:
- "%APPVEYOR_BUILD_FOLDER%/target"

install:
- ps: .\ci\appveyor\install.ps1
- pip install -U -r ci/requirements.txt

before_build:
- python -V
- rustc -V
- cargo -V

build_script:
- python setup.py build_ext --inplace

test_script:
- python setup.py test

before_deploy:
- python setup.py bdist_wheel
- pip install -U twine

deploy_script:
- ps: .\ci\appveyor\deploy.ps1
