
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TOOLCHAIN=nightly
    - PATH="$PYENV_ROOT/bin:$HOME/.cargo/bin:$PATH"
    - PYTHON_SYS_EXECUTABLE="python3"
    - PYENV_ROOT="$HOME/.pyenv"

git:
  depth: false

stages:
  - name: linux
  - name: osx
  - name: coverage

.test-python: &test-python
  stage: linux
  dist: bionic
  language: python
  cache:
    directories:
      - $HOME/.cache/pip
      - $TRAVIS_BUILD_DIR/target
  services:
    - docker
  before_install:
    - ci/travis/manylinux/before_install.sh
  install:
    - ci/travis/manylinux/install.sh
  script:
    - ci/travis/manylinux/script.sh
  after_success:
    - ci/travis/manylinux/after_success.sh

.test-python-osx: &test-python-osx
  stage: osx
  os: osx
  osx_image: xcode7.3
  language: generic
  cache:
    directories:
      - $HOME/.cargo/bin
      - $HOME/.cache/pip
      - $HOME/.pyenv
      - $TRAVIS_BUILD_DIR/target
      - $HOME/Library/Caches/Homebrew
  install:
    - ci/travis/osx/install.sh
  script:
    - ci/travis/osx/script.sh
  before_cache:
    - ci/travis/osx/before_cache.sh
  after_success:
    - ci/travis/osx/after_success.sh

.coverage-python: &coverage-python
  stage: coverage
  dist: bionic
  language: python
  cache:
    directories:
      - $HOME/.cache/pip
      - $TRAVIS_BUILD_DIR/target
  before_install:
    - ci/travis/linux/before_install.sh
  script:
    - ci/travis/linux/tarpaulin.sh
  after_success:
    - curl -s https://codecov.io/bash | bash

jobs:
  allowed_failures:
    - os: osx
      env: PYTHON=pypy3.5
    - os: osx
      env: PYTHON=pypy3.6
  include:
    # Linux
    - python: 3.5
      if: tag IS present
      <<: *test-python
    - python: 3.6
      if: tag IS present
      <<: *test-python
    - python: 3.7
      if: tag IS present
      <<: *test-python
    - python: 3.8
      <<: *test-python
    - python: pypy3
      if: tag IS present
      env: TRAVIS_PYPY_VERSION=7.2.0
      <<: *test-python
    - python: pypy3
      if: tag IS present
      env: TRAVIS_PYPY_VERSION=7.3.1
      <<: *test-python
    # OSX
    - env: PYTHON=python3.5
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=python3.6
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=python3.6
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=python3.7
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=python3.8
      <<: *test-python-osx
    - env: PYTHON=pypy3.5
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=pypy3.6
      if: tag IS present
      <<: *test-python-osx
    - env: PYTHON=pypy3.7
      if: tag IS present
      <<: *test-python-osx
    # Coverage
    - python: 3.8
      if: tag IS blank
      <<: *coverage-python

deploy:
  provider: script
  script: ci/travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: fastobo/fastobo-py

notifications:
  email:
  - althonosdev@gmail.com
